### ISSUE TITLE
UITextfield crash

### ISSUE THREAD

**Issue by WNYFK** [pandamonia/BlocksKit#1]
![11](https://cloud.githubusercontent.com/assets/8078729/8199622/1ea97dec-14eb-11e5-8cd8-67375d5f9109.png)
![22](https://cloud.githubusercontent.com/assets/8078729/8199650/a14961b8-14eb-11e5-8cf6-a7b01a15a5ef.png)
![333](https://cloud.githubusercontent.com/assets/8078729/8199651/a2e578a4-14eb-11e5-9a36-8ea4f19212a3.png)

**Comment by a2** [comment]
This repository is an unmaintained mirror of [zwaldowski/BlocksKit](https://github.com/zwaldowski/BlocksKit). Please file an issue there. Thank you.

**Comment by WNYFK** [comment]
The new version also has the same problem.I use the latest edition.source in https://github.com/zwaldowski/BlocksKit.git ,versions：2.2.5
#import <BlocksKit.h>
@implementation ViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  UITextField *textField = [[UITextField alloc]initWithFrame:CGRectMake(100, 100, 100, 50)];
  textField.borderStyle = UITextBorderStyleRoundedRect;
  [self.view addSubview:textField];
  }

![44](https://cloud.githubusercontent.com/assets/8078729/8208027/bce613c0-1537-11e5-9f7a-2a9d76c453e9.png)

when push in shortcut，crash in shortcut 

![6666](https://cloud.githubusercontent.com/assets/8078729/8208133/75c98f70-1538-11e5-8b87-4fb459156dee.png)

As BlocksKit had Death cycle。
![777](https://cloud.githubusercontent.com/assets/8078729/8208174/b553e2da-1538-11e5-9c67-103b1b911519.png)

**Comment by a2** [comment]
Perhaps I wasn't clear. Please file issues at [zwaldowski/BlocksKit](https://github.com/zwaldowski/BlocksKit).
